# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'revisedVersion.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import socket
import pickle
import threading
import utilities
import numpy as np
import time
import queue
import cv2

from PyQt5 import QtCore, QtGui, QtWidgets

DataVehicleIP = '127.0.0.1'
DataVehiclePort = 8000
DataUiIP = '127.0.0.1'
DataUiPort = 8080


def sendDataThroughSocket(IP, Port, data):
	with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
		s.connect((IP, Port))
		s.sendall(bytes(data, 'utf-8'))
		print("Data: ", data, " sent to IP: ", IP, ", Port: ", Port)


'''
done and checked with this server in mind
import socket

HOST = '127.0.0.1'
PORT = 8000

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
	s.bind((HOST, PORT))
	while True:
		s.listen()
		conn, addr = s.accept()
		print('Connected by', addr)
		data = conn.recv(32)
		if not data:
			pass
		print(data.decode('utf-8'))
'''


def recieveInformationDataSocket(IP, Port):
	with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
		s.bind((IP, Port))
		while True:
			s.listen()
			conn, addr = s.accept()
			print('Connected by', addr)
			data = conn.recv(4096)
			if not data:
				pass
			fetchedInformation = pickle.loads(data)
			print(fetchedInformation)
			# assigning the labels with the data provided


'''
done and checked with this client in mind
import socket, pickle

informationDict = {"time": 45, "travel": "distance", "total distance": 45}


HOST = '127.0.0.1'
PORT = 8080
# Create a socket connection.
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
	s.connect((HOST, PORT))
	data_string = pickle.dumps(informationDict)
	s.send(data_string)

print('Data Sent to Server')
'''


class Ui_Form(QtWidgets.QWidget):

	def __init__(self):
		super().__init__()
		self.conncetionStatus = 0
		self.manualControlStatus = 0
		self.searchStatus = 0
		self.status3D = 0

	def keyPressEvent(self, event):
		print("key press event fired")
		key = event.key()
		# check if state is in manual control and there is a valid connection/socket to send the data through
		# if state in manual - need to be done
		# might need to check connection but we can just send it dont care if we actually know its being recieved

		if key == 16777234 or key == 65:
			# its left arrow button or its a button
			print("left arrow pressed or button A was pressed")
			sendDataThroughSocket(DataVehicleIP, DataVehiclePort, "4")
		elif key == 16777235 or key == 87:
			# its up arrow button or its w button
			print("up arrow pressed or button W was pressed")
			sendDataThroughSocket(DataVehicleIP, DataVehiclePort, "8")
		elif key == 16777236 or key == 68:
			# its right arrow button or its d button
			print("right arrow pressed or button D was pressed")
			sendDataThroughSocket(DataVehicleIP, DataVehiclePort, "6")
		elif key == 16777237 or key == 83:
			# its down arrow button or its s button
			print("down arrow pressed or button S was pressed")
			sendDataThroughSocket(DataVehicleIP, DataVehiclePort, "2")

	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.setWindowModality(QtCore.Qt.ApplicationModal)
		Form.resize(1616, 940)
		Form.setMinimumSize(QtCore.QSize(1616, 940))
		Form.setMaximumSize(QtCore.QSize(1616, 940))
		Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		Form.setAutoFillBackground(False)
		Form.setStyleSheet("#Form{\n"
						   "    background-color:#333;\n"
						   "}\n"
						   "\n"
						   "QPushButton{\n"
						   "    background:linear-gradient(to bottom, #c62d1f 5%, #f24437 100%);\n"
						   "    background-color:#333;\n"
						   "    border-radius:2px;\n"
						   "    color:#eee;\n"
						   "    font-family:Trebuchet MS;\n"
						   "    font-size:12px;\n"
						   "    text-decoration:none;\n"
						   "}\n"
						   "\n"
						   "QFrame{ \n"
						   "    background-color: #444;\n"
						   "    border-radius:2px;\n"
						   "}\n"
						   "\n"
						   "QLabel{\n"
						   "    color:#bbb;\n"
						   "    font-family:Trebuchet MS;\n"
						   "    font-size:12px;\n"
						   "}\n"
						   "\n"
						   "QLabel[cssClass=\"values\"]{\n"
						   "    font-weight:light;\n"
						   "    color:#FDC029;\n"
						   "}\n"
						   "\n"
						   "QLabel[cssClass=\"titles\"]{\n"
						   "    color:#e91;\n"
						   "    font-size:15px;\n"
						   "}\n"
						   "\n"
						   "QLabel[cssClass=\"title2\"]{\n"
						   "    color:#AA3D01;\n"
						   "}\n"
						   "\n"
						   "QComboBox{\n"
						   "    background-color:#292929;\n"
						   "    color:#ffffff;\n"
						   "    font-family:Trebuchet MS;\n"
						   "    font-size:12px;\n"
						   "    font-weight:bold;\n"
						   "    border-radius:2px;\n"
						   "}\n"
						   "\n"
						   "QLineEdit{\n"
						   "    background-color:#292929;\n"
						   "    color:#ffffff;\n"
						   "    font-family:Trebuchet MS;\n"
						   "    font-size:12px;\n"
						   "    border-radius:2px;\n"
						   "}\n"
						   "\n"
						   "QCheckBox{\n"
						   "    color:#262626;\n"
						   "    font-family:Trebuchet MS;\n"
						   "    font-size:12px;\n"
						   "}")
		self.gridLayout = QtWidgets.QGridLayout(Form)
		self.gridLayout.setObjectName("gridLayout")
		self.frame_4 = QtWidgets.QFrame(Form)
		self.frame_4.setMaximumSize(QtCore.QSize(16777215, 281))
		self.frame_4.setStyleSheet("color:#e91;")
		self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.frame_4.setLineWidth(2)
		self.frame_4.setMidLineWidth(0)
		self.frame_4.setObjectName("frame_4")
		self.BTN_8 = QtWidgets.QPushButton(self.frame_4)
		self.BTN_8.setGeometry(QtCore.QRect(930, 80, 130, 130))
		self.BTN_8.setMaximumSize(QtCore.QSize(130, 130))
		self.BTN_8.setStyleSheet("border-radius:65px;\n"
								 "color:rgb(0,200,0);\n"
								 "font-family:Trebuchet MS;\n"
								 "font-size:14px; ")
		self.BTN_8.setObjectName("BTN_8")
		self.GB_5 = QtWidgets.QGroupBox(self.frame_4)
		self.GB_5.setGeometry(QtCore.QRect(9, 10, 841, 261))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.GB_5.setFont(font)
		self.GB_5.setObjectName("GB_5")
		self.LBL_19 = QtWidgets.QLabel(self.GB_5)
		self.LBL_19.setGeometry(QtCore.QRect(60, 120, 101, 16))
		self.LBL_19.setStyleSheet("color:#eee;")
		self.LBL_19.setObjectName("LBL_19")
		self.LBL_24 = QtWidgets.QLabel(self.GB_5)
		self.LBL_24.setGeometry(QtCore.QRect(340, 90, 41, 16))
		self.LBL_24.setStyleSheet("color:#eee;")
		self.LBL_24.setObjectName("LBL_24")
		self.value_avg_speed = QtWidgets.QLabel(self.GB_5)
		self.value_avg_speed.setGeometry(QtCore.QRect(170, 120, 111, 16))
		self.value_avg_speed.setStyleSheet("font-weight:light;\n"
										   "color:#FDC029;")
		self.value_avg_speed.setObjectName("value_avg_speed")
		self.LBL_31 = QtWidgets.QLabel(self.GB_5)
		self.LBL_31.setGeometry(QtCore.QRect(620, 180, 91, 16))
		self.LBL_31.setStyleSheet("color:#eee;")
		self.LBL_31.setObjectName("LBL_31")
		self.LBL_27 = QtWidgets.QLabel(self.GB_5)
		self.LBL_27.setGeometry(QtCore.QRect(620, 60, 71, 16))
		self.LBL_27.setStyleSheet("color:#eee;")
		self.LBL_27.setObjectName("LBL_27")
		self.value_ultrasonic = QtWidgets.QLabel(self.GB_5)
		self.value_ultrasonic.setGeometry(QtCore.QRect(240, 150, 91, 16))
		self.value_ultrasonic.setStyleSheet("font-weight:light;\n"
											"color:#FDC029;")
		self.value_ultrasonic.setObjectName("value_ultrasonic")
		self.LBL_25 = QtWidgets.QLabel(self.GB_5)
		self.LBL_25.setGeometry(QtCore.QRect(340, 120, 61, 16))
		self.LBL_25.setStyleSheet("color:#eee;")
		self.LBL_25.setObjectName("LBL_25")
		self.value_rotation = QtWidgets.QLabel(self.GB_5)
		self.value_rotation.setGeometry(QtCore.QRect(140, 210, 101, 16))
		self.value_rotation.setStyleSheet("font-weight:light;\n"
										  "color:#FDC029;")
		self.value_rotation.setObjectName("value_rotation")
		self.value_raw = QtWidgets.QLabel(self.GB_5)
		self.value_raw.setGeometry(QtCore.QRect(700, 60, 61, 16))
		self.value_raw.setStyleSheet("font-weight:light;\n"
									 "color:#FDC029;")
		self.value_raw.setObjectName("value_raw")
		self.value_depth = QtWidgets.QLabel(self.GB_5)
		self.value_depth.setGeometry(QtCore.QRect(740, 120, 71, 16))
		self.value_depth.setStyleSheet("font-weight:light;\n"
									   "color:#FDC029;")
		self.value_depth.setObjectName("value_depth")
		self.value_motion = QtWidgets.QLabel(self.GB_5)
		self.value_motion.setGeometry(QtCore.QRect(160, 60, 91, 16))
		self.value_motion.setStyleSheet("font-weight:light;\n"
										"color:#FDC029;")
		self.value_motion.setObjectName("value_motion")
		self.LBL_18 = QtWidgets.QLabel(self.GB_5)
		self.LBL_18.setGeometry(QtCore.QRect(60, 90, 121, 16))
		self.LBL_18.setStyleSheet("color:#eee;")
		self.LBL_18.setObjectName("LBL_18")
		self.LBL_20 = QtWidgets.QLabel(self.GB_5)
		self.LBL_20.setGeometry(QtCore.QRect(70, 150, 161, 20))
		self.LBL_20.setStyleSheet("color:#eee;")
		self.LBL_20.setObjectName("LBL_20")
		self.LBL_21 = QtWidgets.QLabel(self.GB_5)
		self.LBL_21.setGeometry(QtCore.QRect(70, 180, 61, 20))
		self.LBL_21.setStyleSheet("color:#eee;")
		self.LBL_21.setObjectName("LBL_21")
		self.LBL_22 = QtWidgets.QLabel(self.GB_5)
		self.LBL_22.setGeometry(QtCore.QRect(70, 210, 61, 16))
		self.LBL_22.setStyleSheet("color:#eee;")
		self.LBL_22.setObjectName("LBL_22")
		self.value_frame = QtWidgets.QLabel(self.GB_5)
		self.value_frame.setGeometry(QtCore.QRect(740, 90, 51, 16))
		self.value_frame.setStyleSheet("font-weight:light;\n"
									   "color:#FDC029;")
		self.value_frame.setObjectName("value_frame")
		self.LBL_28 = QtWidgets.QLabel(self.GB_5)
		self.LBL_28.setGeometry(QtCore.QRect(620, 90, 111, 16))
		self.LBL_28.setStyleSheet("color:#eee;")
		self.LBL_28.setObjectName("LBL_28")
		self.value_distance = QtWidgets.QLabel(self.GB_5)
		self.value_distance.setGeometry(QtCore.QRect(190, 90, 111, 16))
		self.value_distance.setStyleSheet("font-weight:light;\n"
										  "color:#FDC029;")
		self.value_distance.setObjectName("value_distance")
		self.value_3d_status = QtWidgets.QLabel(self.GB_5)
		self.value_3d_status.setGeometry(QtCore.QRect(700, 150, 71, 16))
		self.value_3d_status.setStyleSheet("font-weight:light;\n"
										   "color:#FDC029;")
		self.value_3d_status.setObjectName("value_3d_status")
		self.title_1_2 = QtWidgets.QLabel(self.GB_5)
		self.title_1_2.setGeometry(QtCore.QRect(310, 27, 101, 31))
		self.title_1_2.setStyleSheet("color:#AA3D01;")
		self.title_1_2.setObjectName("title_1_2")
		self.value_mapping = QtWidgets.QLabel(self.GB_5)
		self.value_mapping.setGeometry(QtCore.QRect(720, 180, 81, 16))
		self.value_mapping.setStyleSheet("font-weight:light;\n"
										 "color:#FDC029;")
		self.value_mapping.setObjectName("value_mapping")
		self.LBL_23 = QtWidgets.QLabel(self.GB_5)
		self.LBL_23.setGeometry(QtCore.QRect(340, 60, 141, 16))
		self.LBL_23.setStyleSheet("color:#eee;")
		self.LBL_23.setObjectName("LBL_23")
		self.LBL_30 = QtWidgets.QLabel(self.GB_5)
		self.LBL_30.setGeometry(QtCore.QRect(620, 150, 61, 16))
		self.LBL_30.setStyleSheet("color:#eee;")
		self.LBL_30.setObjectName("LBL_30")
		self.value_blocks = QtWidgets.QLabel(self.GB_5)
		self.value_blocks.setGeometry(QtCore.QRect(390, 90, 101, 16))
		self.value_blocks.setStyleSheet("font-weight:light;\n"
										"color:#FDC029;")
		self.value_blocks.setObjectName("value_blocks")
		self.value_block_size = QtWidgets.QLabel(self.GB_5)
		self.value_block_size.setGeometry(QtCore.QRect(410, 120, 101, 16))
		self.value_block_size.setStyleSheet("font-weight:light;\n"
											"color:#FDC029;")
		self.value_block_size.setObjectName("value_block_size")
		self.value_percentage = QtWidgets.QLabel(self.GB_5)
		self.value_percentage.setGeometry(QtCore.QRect(490, 60, 91, 16))
		self.value_percentage.setStyleSheet("font-weight:light;\n"
											"color:#FDC029;")
		self.value_percentage.setObjectName("value_percentage")
		self.title_1_1 = QtWidgets.QLabel(self.GB_5)
		self.title_1_1.setGeometry(QtCore.QRect(30, 27, 91, 31))
		self.title_1_1.setStyleSheet("color:#AA3D01;")
		self.title_1_1.setObjectName("title_1_1")
		self.value_mapped = QtWidgets.QLabel(self.GB_5)
		self.value_mapped.setGeometry(QtCore.QRect(450, 150, 91, 16))
		self.value_mapped.setStyleSheet("font-weight:light;\n"
										"color:#FDC029;")
		self.value_mapped.setObjectName("value_mapped")
		self.LBL_29 = QtWidgets.QLabel(self.GB_5)
		self.LBL_29.setGeometry(QtCore.QRect(620, 120, 111, 16))
		self.LBL_29.setStyleSheet("color:#eee;")
		self.LBL_29.setObjectName("LBL_29")
		self.LBL_17 = QtWidgets.QLabel(self.GB_5)
		self.LBL_17.setGeometry(QtCore.QRect(60, 60, 91, 16))
		self.LBL_17.setStyleSheet("color:#eee;")
		self.LBL_17.setObjectName("LBL_17")
		self.LBL_26 = QtWidgets.QLabel(self.GB_5)
		self.LBL_26.setGeometry(QtCore.QRect(340, 150, 101, 16))
		self.LBL_26.setStyleSheet("color:#eee;")
		self.LBL_26.setObjectName("LBL_26")
		self.value_location = QtWidgets.QLabel(self.GB_5)
		self.value_location.setGeometry(QtCore.QRect(140, 180, 81, 16))
		self.value_location.setStyleSheet("font-weight:light;\n"
										  "color:#FDC029;")
		self.value_location.setObjectName("value_location")
		self.title_1_3 = QtWidgets.QLabel(self.GB_5)
		self.title_1_3.setGeometry(QtCore.QRect(590, 27, 81, 21))
		self.title_1_3.setStyleSheet("color:#AA3D01;")
		self.title_1_3.setObjectName("title_1_3")
		self.gridLayout.addWidget(self.frame_4, 2, 1, 1, 2)
		self.frame = QtWidgets.QFrame(Form)
		self.frame.setMinimumSize(QtCore.QSize(453, 281))
		self.frame.setMaximumSize(QtCore.QSize(453, 281))
		self.frame.setFrameShape(QtWidgets.QFrame.Panel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.frame.setLineWidth(1)
		self.frame.setMidLineWidth(0)
		self.frame.setObjectName("frame")
		self.GB_1 = QtWidgets.QGroupBox(self.frame)
		self.GB_1.setGeometry(QtCore.QRect(11, 11, 431, 261))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.GB_1.setFont(font)
		self.GB_1.setStyleSheet("color:#e91;")
		self.GB_1.setObjectName("GB_1")
		self.value_status = QtWidgets.QLabel(self.GB_1)
		self.value_status.setGeometry(QtCore.QRect(140, 160, 91, 16))
		self.value_status.setStyleSheet("font-weight:light;\n"
										"color:rgb(220,0,0);")
		self.value_status.setAlignment(QtCore.Qt.AlignCenter)
		self.value_status.setObjectName("value_status")
		self.value_battery = QtWidgets.QLabel(self.GB_1)
		self.value_battery.setGeometry(QtCore.QRect(140, 210, 91, 16))
		self.value_battery.setStyleSheet("font-weight:light;\n"
										 "color:rgb(220,0,0);")
		self.value_battery.setAlignment(QtCore.Qt.AlignCenter)
		self.value_battery.setObjectName("value_battery")
		self.LBL_1 = QtWidgets.QLabel(self.GB_1)
		self.LBL_1.setGeometry(QtCore.QRect(70, 160, 41, 16))
		self.LBL_1.setStyleSheet("color:#eee;")
		self.LBL_1.setObjectName("LBL_1")
		self.LBL_2 = QtWidgets.QLabel(self.GB_1)
		self.LBL_2.setGeometry(QtCore.QRect(70, 210, 51, 16))
		self.LBL_2.setStyleSheet("color:#eee;")
		self.LBL_2.setObjectName("LBL_2")
		self.INP_ip = QtWidgets.QLineEdit(self.GB_1)
		self.INP_ip.setGeometry(QtCore.QRect(70, 70, 120, 26))
		self.INP_ip.setStyleSheet("background-color:#292929;\n"
								  "color:#ffffff;\n"
								  "font-family:Trebuchet MS;\n"
								  "font-size:12px; \n"
								  "border-radius:2px;")
		self.INP_ip.setCursorPosition(0)
		self.INP_ip.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_ip.setObjectName("INP_ip")
		self.INP_port = QtWidgets.QLineEdit(self.GB_1)
		self.INP_port.setGeometry(QtCore.QRect(70, 110, 121, 26))
		self.INP_port.setStyleSheet("background-color:#292929;\n"
									"color:#ffffff;\n"
									"font-family:Trebuchet MS;\n"
									"font-size:12px; \n"
									"border-radius:2px;")
		self.INP_port.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_port.setObjectName("INP_port")
		self.BTN_connect = QtWidgets.QPushButton(self.GB_1)
		self.BTN_connect.setGeometry(QtCore.QRect(210, 90, 95, 26))
		self.BTN_connect.setMinimumSize(QtCore.QSize(95, 26))
		self.BTN_connect.setStyleSheet("color:#eee;")
		self.BTN_connect.setObjectName("BTN_connect")
		self.title_1 = QtWidgets.QLabel(self.GB_1)
		self.title_1.setGeometry(QtCore.QRect(50, 30, 181, 31))
		self.title_1.setStyleSheet("color:#AA3D01;\n"
								   "font-size:15px;")
		self.title_1.setObjectName("title_1")
		self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
		self.frame_5 = QtWidgets.QFrame(Form)
		self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.frame_5.setMidLineWidth(0)
		self.frame_5.setObjectName("frame_5")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.GB_6 = QtWidgets.QGroupBox(self.frame_5)
		font = QtGui.QFont()
		font.setPointSize(11)
		self.GB_6.setFont(font)
		self.GB_6.setStyleSheet("color:#e91;")
		self.GB_6.setAlignment(QtCore.Qt.AlignCenter)
		self.GB_6.setObjectName("GB_6")
		self.path_widget = QtWidgets.QWidget(self.GB_6)
		self.path_widget.setGeometry(QtCore.QRect(10, 30, 411, 541))
		self.path_widget.setAutoFillBackground(False)
		self.path_widget.setStyleSheet("background-color:#000;")
		self.path_widget.setObjectName("path_widget")
		self.verticalLayout_4.addWidget(self.GB_6)
		self.gridLayout.addWidget(self.frame_5, 0, 2, 2, 1)
		self.frame_2 = QtWidgets.QFrame(Form)
		self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
		self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.frame_2.setLineWidth(1)
		self.frame_2.setMidLineWidth(0)
		self.frame_2.setObjectName("frame_2")
		self.GB_2 = QtWidgets.QGroupBox(self.frame_2)
		self.GB_2.setGeometry(QtCore.QRect(10, 10, 431, 231))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.GB_2.setFont(font)
		self.GB_2.setStyleSheet("color:#e91;")
		self.GB_2.setObjectName("GB_2")
		self.title_2 = QtWidgets.QLabel(self.GB_2)
		self.title_2.setGeometry(QtCore.QRect(80, 30, 121, 31))
		self.title_2.setStyleSheet("color:#AA3D01;\n"
								   "font-size:15px;")
		self.title_2.setObjectName("title_2")
		self.LBL_3 = QtWidgets.QLabel(self.GB_2)
		self.LBL_3.setGeometry(QtCore.QRect(100, 70, 47, 13))
		self.LBL_3.setStyleSheet("color:#eee;")
		self.LBL_3.setObjectName("LBL_3")
		self.LBL_5 = QtWidgets.QLabel(self.GB_2)
		self.LBL_5.setGeometry(QtCore.QRect(100, 150, 47, 13))
		self.LBL_5.setStyleSheet("color:#eee;")
		self.LBL_5.setObjectName("LBL_5")
		self.LBL_4 = QtWidgets.QLabel(self.GB_2)
		self.LBL_4.setGeometry(QtCore.QRect(100, 110, 47, 13))
		self.LBL_4.setStyleSheet("color:#eee;")
		self.LBL_4.setObjectName("LBL_4")
		self.LBL_6 = QtWidgets.QLabel(self.GB_2)
		self.LBL_6.setGeometry(QtCore.QRect(100, 190, 47, 13))
		self.LBL_6.setStyleSheet("color:#eee;")
		self.LBL_6.setObjectName("LBL_6")
		self.INP_front_length = QtWidgets.QLineEdit(self.GB_2)
		self.INP_front_length.setGeometry(QtCore.QRect(150, 70, 80, 20))
		self.INP_front_length.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_front_length.setObjectName("INP_front_length")
		self.INP_back_length = QtWidgets.QLineEdit(self.GB_2)
		self.INP_back_length.setGeometry(QtCore.QRect(150, 110, 80, 20))
		self.INP_back_length.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_back_length.setObjectName("INP_back_length")
		self.INP_right_length = QtWidgets.QLineEdit(self.GB_2)
		self.INP_right_length.setGeometry(QtCore.QRect(150, 150, 80, 20))
		self.INP_right_length.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_right_length.setObjectName("INP_right_length")
		self.INP_left_length = QtWidgets.QLineEdit(self.GB_2)
		self.INP_left_length.setGeometry(QtCore.QRect(150, 190, 80, 20))
		self.INP_left_length.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_left_length.setObjectName("INP_left_length")
		self.LBL_13 = QtWidgets.QLabel(self.GB_2)
		self.LBL_13.setGeometry(QtCore.QRect(240, 70, 47, 13))
		self.LBL_13.setStyleSheet("color:#eee;")
		self.LBL_13.setObjectName("LBL_13")
		self.LBL_14 = QtWidgets.QLabel(self.GB_2)
		self.LBL_14.setGeometry(QtCore.QRect(240, 110, 47, 13))
		self.LBL_14.setStyleSheet("color:#eee;")
		self.LBL_14.setObjectName("LBL_14")
		self.LBL_15 = QtWidgets.QLabel(self.GB_2)
		self.LBL_15.setGeometry(QtCore.QRect(240, 150, 47, 13))
		self.LBL_15.setStyleSheet("color:#eee;")
		self.LBL_15.setObjectName("LBL_15")
		self.LBL_16 = QtWidgets.QLabel(self.GB_2)
		self.LBL_16.setGeometry(QtCore.QRect(240, 190, 47, 13))
		self.LBL_16.setStyleSheet("color:#eee;")
		self.LBL_16.setObjectName("LBL_16")
		self.GB_3 = QtWidgets.QGroupBox(self.frame_2)
		self.GB_3.setGeometry(QtCore.QRect(10, 250, 431, 271))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.GB_3.setFont(font)
		self.GB_3.setStyleSheet("color:#e91;")
		self.GB_3.setObjectName("GB_3")
		self.LBL_7 = QtWidgets.QLabel(self.GB_3)
		self.LBL_7.setGeometry(QtCore.QRect(50, 30, 111, 16))
		self.LBL_7.setStyleSheet("color:#eee;")
		self.LBL_7.setObjectName("LBL_7")
		self.LBL_8 = QtWidgets.QLabel(self.GB_3)
		self.LBL_8.setGeometry(QtCore.QRect(50, 70, 121, 16))
		self.LBL_8.setStyleSheet("color:#eee;")
		self.LBL_8.setObjectName("LBL_8")
		self.LBL_9 = QtWidgets.QLabel(self.GB_3)
		self.LBL_9.setGeometry(QtCore.QRect(50, 110, 111, 16))
		self.LBL_9.setStyleSheet("color:#eee;")
		self.LBL_9.setObjectName("LBL_9")
		self.LBL_10 = QtWidgets.QLabel(self.GB_3)
		self.LBL_10.setGeometry(QtCore.QRect(50, 150, 81, 16))
		self.LBL_10.setStyleSheet("color:#eee;")
		self.LBL_10.setObjectName("LBL_10")
		self.LBL_11 = QtWidgets.QLabel(self.GB_3)
		self.LBL_11.setGeometry(QtCore.QRect(50, 190, 81, 16))
		self.LBL_11.setStyleSheet("color:#eee;")
		self.LBL_11.setObjectName("LBL_11")
		self.LBL_12 = QtWidgets.QLabel(self.GB_3)
		self.LBL_12.setGeometry(QtCore.QRect(50, 230, 91, 16))
		self.LBL_12.setStyleSheet("color:#eee;")
		self.LBL_12.setObjectName("LBL_12")
		self.INP_model = QtWidgets.QLineEdit(self.GB_3)
		self.INP_model.setGeometry(QtCore.QRect(170, 30, 80, 20))
		self.INP_model.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_model.setObjectName("INP_model")
		self.INP_bubble = QtWidgets.QLineEdit(self.GB_3)
		self.INP_bubble.setGeometry(QtCore.QRect(170, 70, 80, 20))
		self.INP_bubble.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_bubble.setObjectName("INP_bubble")
		self.INP_block = QtWidgets.QLineEdit(self.GB_3)
		self.INP_block.setGeometry(QtCore.QRect(170, 110, 80, 20))
		self.INP_block.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_block.setObjectName("INP_block")
		self.INP_point = QtWidgets.QLineEdit(self.GB_3)
		self.INP_point.setGeometry(QtCore.QRect(170, 150, 80, 20))
		self.INP_point.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_point.setObjectName("INP_point")
		self.INP_cloud = QtWidgets.QLineEdit(self.GB_3)
		self.INP_cloud.setGeometry(QtCore.QRect(170, 190, 80, 20))
		self.INP_cloud.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_cloud.setObjectName("INP_cloud")
		self.INP_slant = QtWidgets.QLineEdit(self.GB_3)
		self.INP_slant.setGeometry(QtCore.QRect(170, 230, 80, 20))
		self.INP_slant.setAlignment(QtCore.Qt.AlignCenter)
		self.INP_slant.setObjectName("INP_slant")
		self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 530, 431, 28))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(
			self.horizontalLayoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.BTN_search_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
		self.BTN_search_2.setMinimumSize(QtCore.QSize(180, 26))
		self.BTN_search_2.setMaximumSize(QtCore.QSize(180, 16777215))
		self.BTN_search_2.setObjectName("BTN_search_2")
		self.horizontalLayout.addWidget(
			self.BTN_search_2, 0, QtCore.Qt.AlignHCenter)
		self.BTN_abort_search = QtWidgets.QPushButton(
			self.horizontalLayoutWidget)
		self.BTN_abort_search.setMinimumSize(QtCore.QSize(180, 26))
		self.BTN_abort_search.setObjectName("BTN_abort_search")
		self.horizontalLayout.addWidget(
			self.BTN_abort_search, 0, QtCore.Qt.AlignHCenter)
		self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
		self.horizontalLayoutWidget_2.setGeometry(
			QtCore.QRect(10, 570, 431, 28))
		self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
			self.horizontalLayoutWidget_2)
		self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.BTN_check = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
		self.BTN_check.setMinimumSize(QtCore.QSize(180, 26))
		self.BTN_check.setMaximumSize(QtCore.QSize(180, 16777215))
		self.BTN_check.setObjectName("BTN_check")
		self.horizontalLayout_2.addWidget(
			self.BTN_check, 0, QtCore.Qt.AlignHCenter)
		self.BTN_MC = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
		self.BTN_MC.setMinimumSize(QtCore.QSize(180, 26))
		self.BTN_MC.setObjectName("BTN_MC")
		self.horizontalLayout_2.addWidget(
			self.BTN_MC, 0, QtCore.Qt.AlignHCenter)
		self.gridLayout.addWidget(self.frame_2, 1, 0, 2, 1)
		self.frame_6 = QtWidgets.QFrame(Form)
		sizePolicy = QtWidgets.QSizePolicy(
			QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(
			self.frame_6.sizePolicy().hasHeightForWidth())
		self.frame_6.setSizePolicy(sizePolicy)
		self.frame_6.setMinimumSize(QtCore.QSize(0, 23))
		self.frame_6.setMaximumSize(QtCore.QSize(16777215, 23))
		self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.frame_6.setMidLineWidth(0)
		self.frame_6.setObjectName("frame_6")
		self.layoutWidget = QtWidgets.QWidget(self.frame_6)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 1571, 22))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_17.setObjectName("horizontalLayout_17")
		self.LBL_32 = QtWidgets.QLabel(self.layoutWidget)
		self.LBL_32.setObjectName("LBL_32")
		self.horizontalLayout_17.addWidget(self.LBL_32)
		self.value_18 = QtWidgets.QLabel(self.layoutWidget)
		self.value_18.setStyleSheet("color:#e91;")
		self.value_18.setObjectName("value_18")
		self.horizontalLayout_17.addWidget(self.value_18)
		spacerItem = QtWidgets.QSpacerItem(
			40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_17.addItem(spacerItem)
		self.LBL_33 = QtWidgets.QLabel(self.layoutWidget)
		self.LBL_33.setObjectName("LBL_33")
		self.horizontalLayout_17.addWidget(
			self.LBL_33, 0, QtCore.Qt.AlignRight)
		self.value_19 = QtWidgets.QLabel(self.layoutWidget)
		self.value_19.setStyleSheet("color:#e91;")
		self.value_19.setObjectName("value_19")
		self.horizontalLayout_17.addWidget(
			self.value_19, 0, QtCore.Qt.AlignLeft)
		self.gridLayout.addWidget(self.frame_6, 3, 0, 1, 3)
		self.frame_3 = QtWidgets.QFrame(Form)
		self.frame_3.setMinimumSize(QtCore.QSize(680, 606))
		self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.frame_3.setMidLineWidth(0)
		self.frame_3.setObjectName("frame_3")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
		self.verticalLayout.setObjectName("verticalLayout")
		self.GB_4 = QtWidgets.QGroupBox(self.frame_3)
		font = QtGui.QFont()
		font.setPointSize(11)
		self.GB_4.setFont(font)
		self.GB_4.setStyleSheet("color:#e91;")
		self.GB_4.setAlignment(QtCore.Qt.AlignCenter)
		self.GB_4.setObjectName("GB_4")
		self.layoutWidget1 = QtWidgets.QWidget(self.GB_4)
		self.layoutWidget1.setGeometry(QtCore.QRect(10, 520, 641, 61))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
		self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.BTN_raw = QtWidgets.QPushButton(self.layoutWidget1)
		self.BTN_raw.setMinimumSize(QtCore.QSize(100, 35))
		self.BTN_raw.setMaximumSize(QtCore.QSize(70, 16777215))
		self.BTN_raw.setStyleSheet("color:#eee;")
		self.BTN_raw.setObjectName("BTN_raw")
		self.horizontalLayout_5.addWidget(self.BTN_raw)
		self.BTN_depth = QtWidgets.QPushButton(self.layoutWidget1)
		self.BTN_depth.setMinimumSize(QtCore.QSize(100, 35))
		self.BTN_depth.setMaximumSize(QtCore.QSize(70, 16777215))
		self.BTN_depth.setStyleSheet("color:#eee;")
		self.BTN_depth.setObjectName("BTN_depth")
		self.horizontalLayout_5.addWidget(self.BTN_depth)
		self.BTN_edge = QtWidgets.QPushButton(self.layoutWidget1)
		self.BTN_edge.setMinimumSize(QtCore.QSize(100, 35))
		self.BTN_edge.setMaximumSize(QtCore.QSize(70, 16777215))
		self.BTN_edge.setStyleSheet("color:#eee;")
		self.BTN_edge.setObjectName("BTN_edge")
		self.horizontalLayout_5.addWidget(self.BTN_edge)
		self.img_widget = QtWidgets.QWidget(self.GB_4)
		self.img_widget.setGeometry(QtCore.QRect(10, 40, 640, 480))
		# self.img_widget.setAutoFillBackground(False)
		# self.img_widget.setStyleSheet("background-color:#000;")
		self.img_widget.setObjectName("img_widget")
		self.verticalLayout.addWidget(self.GB_4)
		self.gridLayout.addWidget(self.frame_3, 0, 1, 2, 1)

		self.grabKeyboard()

		# Button Action Assignment
		# Action and Input side buttons
		# connect button
		# self.BTN_connect.clicked.connect(self.connect())
		# # start exploration button(gonna be BTN_search)
		# self.BTN_search_2.clicked.connect(self.startSearch())
		# # abort exploration button
		# self.BTN_abort_search.clicked.connect(self.abortSearch())
		# # check system button
		self.BTN_check.clicked.connect(self.checkSystem)
		# # manual control button
		# self.BTN_MC.connect(self.manualControl())

		# # Video formatting Buttons
		# # raw button
		# self.BTN_raw.clicked.connect(self.changeFeedToRaw())
		self.BTN_raw.clicked.connect(self.button)
		# # depth button
		# self.BTN_raw.clicked.connect(self.changeFeedToDepth())
		# # edge button
		# self.BTN_raw.clicked.connect(self.changeFeedToEdge())

		# 3D Viewing
		# Explore 3D button(gonna be BTN_explore)
		# self.BTN_8.clicked.connect(self.explore3D())

		self.window_width = self.img_widget.frameSize().width()
		self.window_height = self.img_widget.frameSize().height()
		self.img_widget = OwnImageWidget(self.img_widget)
		self.q = queue.Queue()

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Prometheus"))
		self.BTN_8.setText(_translate("Form", "Explore 3D"))
		self.GB_5.setTitle(_translate("Form", " Information "))
		self.LBL_19.setText(_translate("Form", "   Average Speed :"))
		self.LBL_24.setText(_translate("Form", "Blocks :"))
		self.value_avg_speed.setText(_translate("Form", "--"))
		self.LBL_31.setText(_translate("Form", "Mapping Time :"))
		self.LBL_27.setText(_translate("Form", "Raw Frames :"))
		self.value_ultrasonic.setText(_translate("Form", "--"))
		self.LBL_25.setText(_translate("Form", "Block Size :"))
		self.value_rotation.setText(_translate("Form", "--"))
		self.value_raw.setText(_translate("Form", "--"))
		self.value_depth.setText(_translate("Form", "--"))
		self.value_motion.setText(_translate("Form", "--"))
		self.LBL_18.setText(_translate("Form", "   Distance Covered :"))
		self.LBL_20.setText(_translate("Form", "UltraSonic Sensor Distance :"))
		self.LBL_21.setText(_translate("Form", "Location :"))
		self.LBL_22.setText(_translate("Form", "Rotation :"))
		self.value_frame.setText(_translate("Form", "--"))
		self.LBL_28.setText(_translate("Form", "Frames Reduced :"))
		self.value_distance.setText(_translate("Form", "--"))
		self.value_3d_status.setText(_translate("Form", "--"))
		self.title_1_2.setText(_translate("Form", "Block Data"))
		self.value_mapping.setText(_translate("Form", "--"))
		self.LBL_23.setText(_translate("Form", "Occupation Percentage :"))
		self.LBL_30.setText(_translate("Form", "3D Status :"))
		self.value_blocks.setText(_translate("Form", "--"))
		self.value_block_size.setText(_translate("Form", "--"))
		self.value_percentage.setText(_translate("Form", "--"))
		self.title_1_1.setText(_translate("Form", "Drone Data"))
		self.value_mapped.setText(_translate("Form", "--"))
		self.LBL_29.setText(_translate("Form", "Depth Processed :"))
		self.LBL_17.setText(_translate("Form", "   Motion Time :"))
		self.LBL_26.setText(_translate("Form", "Mapped Volume :"))
		self.value_location.setText(_translate("Form", "--"))
		self.title_1_3.setText(_translate("Form", "General"))
		self.GB_1.setTitle(_translate("Form", " Connect Vehicle "))
		self.value_status.setText(_translate("Form", "Unconnected"))
		self.value_battery.setText(_translate("Form", "--"))
		self.LBL_1.setText(_translate("Form", "Status :"))
		self.LBL_2.setText(_translate("Form", "Battery :"))
		self.INP_ip.setPlaceholderText(_translate("Form", "IP Address"))
		self.INP_port.setPlaceholderText(_translate("Form", "Port"))
		self.BTN_connect.setText(_translate("Form", "Connect"))
		self.title_1.setText(_translate("Form", "Add Vehicle"))
		self.GB_6.setTitle(_translate(
			"Form", " Vehicle Movement Visualization "))
		self.GB_2.setTitle(_translate("Form", " Navigation Parameters "))
		self.title_2.setText(_translate("Form", "Boundaries"))
		self.LBL_3.setText(_translate("Form", "Front :"))
		self.LBL_5.setText(_translate("Form", "Right :"))
		self.LBL_4.setText(_translate("Form", "Back :"))
		self.LBL_6.setText(_translate("Form", "Left :"))
		self.INP_front_length.setStyleSheet(_translate("Form", "background-color:#292929;\n"
													   "color:#ffffff;\n"
													   "font-family:Trebuchet MS;\n"
													   "font-size:12px; \n"
													   "border-radius:2px;"))
		self.INP_back_length.setStyleSheet(_translate("Form", "background-color:#292929;\n"
													  "color:#ffffff;\n"
													  "font-family:Trebuchet MS;\n"
													  "font-size:12px; \n"
													  "border-radius:2px;"))
		self.INP_right_length.setStyleSheet(_translate("Form", "background-color:#292929;\n"
													   "color:#ffffff;\n"
													   "font-family:Trebuchet MS;\n"
													   "font-size:12px; \n"
													   "border-radius:2px;"))
		self.INP_left_length.setStyleSheet(_translate("Form", "background-color:#292929;\n"
													  "color:#ffffff;\n"
													  "font-family:Trebuchet MS;\n"
													  "font-size:12px; \n"
													  "border-radius:2px;"))
		self.LBL_13.setText(_translate("Form", "m"))
		self.LBL_14.setText(_translate("Form", "m"))
		self.LBL_15.setText(_translate("Form", "m"))
		self.LBL_16.setText(_translate("Form", "m"))
		self.GB_3.setTitle(_translate("Form", " Mapping Parameters "))
		self.LBL_7.setText(_translate("Form", "Model Threshold :"))
		self.LBL_8.setText(_translate("Form", "Bubble Resolution :"))
		self.LBL_9.setText(_translate("Form", "Block Resolution :"))
		self.LBL_10.setText(_translate("Form", "Point Scale :"))
		self.LBL_11.setText(_translate("Form", "Cloud Scale :"))
		self.LBL_12.setText(_translate("Form", "Slant Separation :"))
		self.INP_model.setStyleSheet(_translate("Form", "background-color:#292929;\n"
												"color:#ffffff;\n"
												"font-family:Trebuchet MS;\n"
												"font-size:12px; \n"
												"border-radius:2px;"))
		self.INP_model.setPlaceholderText(_translate("Form", "0 - 1"))
		self.INP_bubble.setStyleSheet(_translate("Form", "background-color:#292929;\n"
												 "color:#ffffff;\n"
												 "font-family:Trebuchet MS;\n"
												 "font-size:12px; \n"
												 "border-radius:2px;"))
		self.INP_bubble.setPlaceholderText(_translate("Form", "1 - 10 ODD"))
		self.INP_block.setStyleSheet(_translate("Form", "background-color:#292929;\n"
												"color:#ffffff;\n"
												"font-family:Trebuchet MS;\n"
												"font-size:12px; \n"
												"border-radius:2px;"))
		self.INP_block.setPlaceholderText(_translate("Form", "32 - 128"))
		self.INP_point.setStyleSheet(_translate("Form", "background-color:#292929;\n"
												"color:#ffffff;\n"
												"font-family:Trebuchet MS;\n"
												"font-size:12px; \n"
												"border-radius:2px;"))
		self.INP_point.setPlaceholderText(_translate("Form", "1 - 100"))
		self.INP_cloud.setStyleSheet(_translate("Form", "background-color:#292929;\n"
												"color:#ffffff;\n"
												"font-family:Trebuchet MS;\n"
												"font-size:12px; \n"
												"border-radius:2px;"))
		self.INP_cloud.setPlaceholderText(_translate("Form", "1 - 100"))
		self.INP_slant.setStyleSheet(_translate("Form", "background-color:#292929;\n"
												"color:#ffffff;\n"
												"font-family:Trebuchet MS;\n"
												"font-size:12px; \n"
												"border-radius:2px;"))
		self.INP_slant.setPlaceholderText(_translate("Form", "0 - 10"))
		self.BTN_search_2.setText(_translate("Form", "Begin Search"))
		self.BTN_abort_search.setText(_translate("Form", "Abort Search"))
		self.BTN_check.setText(_translate("Form", "Check System"))
		self.BTN_MC.setText(_translate("Form", "Switch To Manual Control"))
		self.LBL_32.setText(_translate("Form", "Status: "))
		self.value_18.setText(_translate("Form", "Idle"))
		self.LBL_33.setText(_translate("Form", "Version: "))
		self.value_19.setText(_translate("Form", "1.0"))
		self.GB_4.setTitle(_translate("Form", " Vehicle Video Feed "))
		self.BTN_raw.setText(_translate("Form", "Raw"))
		self.BTN_depth.setText(_translate("Form", "Depth"))
		self.BTN_edge.setText(_translate("Form", "Edge"))

	def button(self):
		self.timer = QtCore.QTimer(self)
		self.timer.timeout.connect(self.update_frame)
		self.timer.start(1)
		myThread = threading.Thread(target=self.grab, args=(
			0, self.q, 1920, 1080, 30), daemon=True)
		myThread.start()

	def update_frame(self):
		# print("update frame called")
		if not self.q.empty():
			frame = self.q.get()
			img = frame["img"]

			img_height, img_width, img_colors = img.shape
			scale_w = float(self.window_width) / float(img_width)
			scale_h = float(self.window_height) / float(img_height)
			scale = min([scale_w, scale_h])

			if scale == 0:
				scale = 1

			img = cv2.resize(img, None, fx=scale, fy=scale, interpolation = cv2.INTER_CUBIC)
			img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
			height, width, bpc = img.shape
			bpl = bpc * width
			image = QtGui.QImage(img.data, width, height, bpl, QtGui.QImage.Format_RGB888)
			self.img_widget.setImage(image)

	def grab(self,cam, queue, width, height, fps):
		print("grab called")
		capture = cv2.VideoCapture('http://192.168.1.105:4747/video')
		capture.set(cv2.CAP_PROP_FRAME_WIDTH, width)
		capture.set(cv2.CAP_PROP_FRAME_HEIGHT, height)
		capture.set(cv2.CAP_PROP_FPS, fps)

		while True:
			print("in grab loop")
			frame = {}
			capture.grab()
			retval, img = capture.retrieve(0)
			frame["img"] = img

			if queue.qsize() < 10:
				queue.put(frame)
			else:
				print(queue.qsize())


	def connect(self):
		ip = self.INP_ip.text()
		port = self.INP_port.text()
		if utilities.validateIP(ip) and utilities.validatePort(port):
			# try connection
			# if connection set self.connectionStatus = 1
			pass

	def startSearch(self):
		self.status3D = 0
		navigation_input_dict = {"frontDist":self.INP_front_length.text(),"backDist":self.INP_back_length.text(),"rightDist":self.INP_right_length.text(),"leftDist":self.INP_left_length.text()}
		mapping_input_dict = {"model":self.INP_model.text(),"bubble":self.INP_bubble.text(),"block":self.INP_block.text(),"point":self.INP_point.text(),"cloud":self.INP_cloud.text(),"slant":self.INP_slant.text()}

		if utilities.validateNavInputs(navigation_input_dict) and utilities.validateMappingInputs(mapping_input_dict):
			# self.manualcontrolstatus = 0
			# start search
			# update search status set self.searching = 1
			pass

	def abortSearch(self):
		pass
		# if self.searchStatus == 1:
		# 	#send abort command to drone
		# 	# assign self.searchstatus when drone approval comes
		# 	self.searchStatus = 0
		# else:
		# 	#vehicle was not searching so nothing to do
		# 	pass

	def checkSystem(self):
		# send checksystem command to vehicle
		# get output message saying check system complete from vehicle and assign it to message
		message = "Check System was successful"
		QtWidgets.QMessageBox.information(self, "Check System", message)

	def manualControl(self):
		if self.manualControlStatus == 0:
			self.manualControlStatus = 1

	def changeFeedToRaw(self):
		if self.feedTypeStatus != "raw":
			self.feedTypeStatus = "raw"

	def changeFeedToDepth(self):
		if self.feedTypeStatus != "depth":
			self.feedTypeStatus = "depth"

	def changeFeedToEdge(self):
		if self.feedTypeStatus != "edge":
			self.feedTypeStatus = "edge"

	def explore3D(self):
		if self.status3D == 1:
			# open the 3D exploring window
			pass

class OwnImageWidget(QtWidgets.QWidget):
		def __init__(self, parent=None):
			super(OwnImageWidget, self).__init__(parent)
			self.image = None

		def setImage(self, image):
			self.image = image
			sz = image.size()
			self.setMinimumSize(sz)
			self.update()

		def paintEvent(self, event):
			qp = QtGui.QPainter()
			qp.begin(self)
			if self.image:
				qp.drawImage(QtCore.QPoint(0, 0), self.image)
			qp.end()

if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	Form = QtWidgets.QWidget()
	ui = Ui_Form()
	ui.setupUi(Form)
	Form.show()
	# Threading added for the a socket server to recieve the information from the vehicle
	DataUiThread = threading.Thread(
		target=recieveInformationDataSocket, args=(DataUiIP, DataUiPort,), daemon=True)
	DataUiThread.start()
	# end
	sys.exit(app.exec_())
